export const ADD_BOOKS_TO_BOOK_LIST = "ADD_BOOKS_TO_BOOK_LIST";
export const SET_LOADING_BOOKS_LIST_DATA_STATUS =
  "SET_LOADING_BOOKS_LIST_DATA_STATUS";
export const SET_LOADING_BOOK_DETAILS_DATA_STATUS =
  "SET_LOADING_BOOK_DETAILS_DATA_STATUS";
export const INCREMENT_START_INDEX = "INCREMENT_START_INDEX";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
